custom alloc error handler called!
error: abnormal termination: the program aborted execution
  --> $DIR/alloc_error_handler_no_std.rs:LL:CC
   |
LL |     core::intrinsics::abort();
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ the program aborted execution
   |
   = note: BACKTRACE:
   = note: inside `alloc_error_handler` at $DIR/alloc_error_handler_no_std.rs:LL:CC
note: inside `_::__rg_oom`
  --> $DIR/alloc_error_handler_no_std.rs:LL:CC
   |
LL | #[alloc_error_handler]
   | ---------------------- in this procedural macro expansion
LL | fn alloc_error_handler(_: Layout) -> ! {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: inside `alloc::alloc::handle_alloc_error::rt_error` at RUSTLIB/alloc/src/alloc.rs:LL:CC
   = note: inside `alloc::alloc::handle_alloc_error` at RUSTLIB/alloc/src/alloc.rs:LL:CC
   = note: inside `alloc::boxed::Box::<i32, BadAlloc>::new_uninit_in` at RUSTLIB/alloc/src/boxed.rs:LL:CC
   = note: inside `alloc::boxed::Box::<i32, BadAlloc>::new_in` at RUSTLIB/alloc/src/boxed.rs:LL:CC
note: inside `start`
  --> $DIR/alloc_error_handler_no_std.rs:LL:CC
   |
LL |     let _b = Box::new_in(0, BadAlloc);
   |              ^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in the attribute macro `alloc_error_handler` (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 1 previous error

